// modules/multiqc.nf
// Run MultiQC over all bcftools stats for one cohort

process MULTIQC {
    label 'process_medium'
    tag  "${cohort}"

    publishDir "${params.results_dir}/${cohort}/qc", mode: 'copy'

    input:
    tuple val(cohort), val(samples), path(stats_files)

    output:
    tuple val(cohort), path("multiqc_${cohort}.html"),  emit: report
    tuple val(cohort), path("multiqc_${cohort}_data/"), emit: data

    script:
    """
    multiqc . \
        --filename multiqc_${cohort} \
        --title "Cohort ${cohort} — Variant QC" \
        --comment "Generated by variant-qc-pipeline v1.0.0" \
        --force \
        --no-megaqc-upload
    """
}
